type BillingAddress {
  location: String
  state: String
  city: String
  country: String
  zipcode: String
  isdefault: Boolean
}

type ShippingAddress {
  location: String
  state: String
  city: String
  country: String
  zipcode: String
  isdefault: Boolean
}

type CustomerContactPerson {
  contact_first_name: String
  contact_last_name: String
  contact_email: String
  contact_phone: String
  contact_job_role: String
}

type Customer {
  userid: Int
  customerid: Int
  category: String
  company_name: String
  email: String
  main_phone: String
  work_phone: String
  first_name: String
  middle_name: String
  last_name: String
  display_name: String
  website: String
  amount: String
  currency: String
  payment_terms: String
  billing_address: [BillingAddress]
  shipping_address: [ShippingAddress]
  customer_contact_person: [CustomerContactPerson]
}

input BillingAddressInput {
  location: String
  state: String
  city: String
  country: String
  zipcode: String
  isdefault: Boolean
}

input ShippingAddressInput {
  location: String
  state: String
  city: String
  country: String
  zipcode: String
  isdefault: Boolean
}

input CustomerContactPersonInput {
  contact_first_name: String
  contact_last_name: String
  contact_email: String
  contact_phone: String
  contact_job_role: String
}

type GetCustomerResponse {
  code: Int
  status: String
  data: Customer
}

type GetCustomerListResponse {
  data: [Customer]
}

type Query {
  getCustomers: GetCustomerListResponse
  getCustomer(id: ID!): GetCustomerResponse
}

type Mutation {
  saveCustomer(
    userid: Int
    customerid: Int
    category: String
    company_name: String
    email: String
    main_phone: String
    work_phone: String
    first_name: String
    middle_name: String
    last_name: String
    display_name: String
    website: String
    amount: String
    currency: String
    payment_terms: String
    billing_address: [BillingAddressInput]
    shipping_address: [ShippingAddressInput]
    customer_contact_person: [CustomerContactPersonInput]
  ): Customer
}
