# const { GraphQLUpload } = require('graphql-upload');
scalar Upload


type Item {
  userid: Int
  itemid: Int
  item_image: String
  item_name: String
  item_code: String
  category: String
  status: String
  purchase_price: Float 
  sales_price: Float
  stock_quantity: Int
  income_account: String
  cogs_account: String
  inventory_account: String
  currency: String
}

type getItemsResponse {
  code: Int
  status: String
  data: Item
}

type getItemListResponse {
  code: Int
  status: String
  data: [Item]
}

type Query {
  getItems: getItemListResponse
  getItem(id: ID!): getItemsResponse
}

type Mutation {
  saveItem(
    userid: Int
    itemid: Int
    image: Upload
    item_image: String
    item_name: String
    item_code: String
    category: String
    status: String
    purchase_price: Float 
    sales_price: Float
    stock_quantity: Int
    income_account: String
    cogs_account: String
    inventory_account: String
    currency: String
  ): Item
}
