# type Vendor {
#   userid: Int
#   vendorid: Int
#   category: String
#   company_name: String
#   email: String
#   main_phone: String
#   work_phone: String
#   first_name: String
#   middle_name: String
#   last_name: String
#   display_name: String
#   website: String
#   amount: String
#   currency: String
#   payment_terms: String
#   vendor_billing_address: [VendorBillingAddress]
#   vendor_shipping_addresses: [VendorShippingAddress]
#   vendor_contact_person: [VendorContactPerson]
# }

# type VendorBillingAddress {
#   location: String
#   state: String
#   city: String
#   country: String
#   zipcode: String
#   isdefault: Boolean
# }

# type VendorShippingAddress {
#   location: String
#   state: String
#   city: String
#   country: String
#   zipcode: String
#   isdefault: Boolean
# }

# type VendorContactPerson {
#   contact_first_name: String
#   contact_last_name: String
#   contact_email: String
#   contact_phone: String
#   contact_job_role: String
# }

# input vendor_billing_address_Input {
#   userid: Int
#   vendorid: Int
#   location: String
#   billing_state: String
#   billing_city: String
#   billing_country: String
#   billing_zipcode: String
#   billing_isdefault: Boolean

# }

# input ShippingAddressInput {
#   userid: Int
#   vendorid: Int
#   shipping_location: String
#   shipping_state: String
#   shipping_city: String
#   shipping_country: String
#   shipping_zipcode: String
#   shipping_isdefault: Boolean

# }

# input VendorContactPersonInput {
#   userid: Int
#   vendorid: Int
#   contact_first_name: String
#   contact_last_name: String
#   contact_email: String
#   contact_phone: String
#   contact_job_role: String
#   }

# type GetVendorResponse {
#   code: Int
#   status: String
#   data: Vendor
# }

# type GetVendorListResponse {
#   code: Int
#   status: String
#   data: [Vendor]
# }

# type Query {
#   getVendors: GetVendorListResponse
#   getVendor(id: ID!): GetVendorResponse
# }

# type Mutation {
#   saveVendor(
#     userid: Int
#     vendorid: Int
#     category: String
#     company_name: String
#     email: String
#     main_phone: String
#     work_phone: String
#     first_name: String
#     middle_name: String
#     last_name: String
#     display_name: String
#     website: String
#     amount: String
#     currency: String
#     payment_terms: String
#     vendor_billing_address: [vendor_billing_address_Input]
#     vendor_shipping_addresses: [ShippingAddressInput]
#     vendor_contact_person: [VendorContactPersonInput]
#   ): Vendor
# }
type Vendor {
  userid: Int
  vendorid: Int
  category: String
  company_name: String
  email: String
  main_phone: String
  work_phone: String
  first_name: String
  middle_name: String
  last_name: String
  display_name: String
  website: String
  amount: String
  currency: String
  payment_terms: String
  vendor_billing_address: [VendorBillingAddress]
  vendor_shipping_addresses: [VendorShippingAddress]
  vendor_contact_person: [VendorContactPerson]
}

type VendorBillingAddress {
  userid:Int
  vendorid:Int 
  location: String
  state: String
  city: String
  country: String
  zipcode: String
  isdefault: Boolean
}

type VendorShippingAddress {
  location: String
  state: String
  city: String
  country: String
  zipcode: String
  isdefault: Boolean
}

type VendorContactPerson {
  contact_first_name: String
  contact_last_name: String
  contact_email: String
  contact_phone: String
  contact_job_role: String
}

input vendor_billing_address_Input {
  vendorid: Int
  location: String
  state: String
  city: String
  country: String
  zipcode: String
  isdefault: Boolean
}

input vendor_Shipping_Address_Input {
  vendorid: Int
  location: String
  state: String
  city: String
  country: String
  zipcode: String
  isdefault: Boolean
}

input Vendor_Contact_Person_Input {
  vendorid: Int
  contact_first_name: String
  contact_last_name: String
  contact_email: String
  contact_phone: String
  contact_job_role: String
  }

type GetVendorResponse {
  code: Int
  status: String
  data: Vendor
}

type GetVendorListResponse {
  code: Int
  status: String
  data: [Vendor]
}

type Query {
  getVendors: GetVendorListResponse
  getVendor(id: ID!): GetVendorResponse
}

type Mutation {
  saveVendor(
    userid: Int
    vendorid: Int
    category: String
    company_name: String
    email: String
    main_phone: String
    work_phone: String
    first_name: String
    middle_name: String
    last_name: String
    display_name: String
    website: String
    amount: String
    currency: String
    payment_terms: String
    vendor_billing_address: [vendor_billing_address_Input]
    vendor_shipping_addresses: [vendor_Shipping_Address_Input]
    vendor_contact_person: [Vendor_Contact_Person_Input]
  ): Vendor
}


